DEBUG    temporalio.worker._activity:_activity.py:276 Running activity run (token b'\n$e6d2a310-ce30-4dfe-87db-9ed829a8df47\x12$556db796-dd96-4ccc-a317-068b9d8d72ba\x1a$56bc9036-0768-4a2d-a521-a72058b3b415 \x05(\x012\x011B\x03runJ\x08\x08\x01\x10\xb5\x96@\x18\x01')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'run', 'attempt': 1, 'namespace': 'default', 'task_queue': '3a2d4a37-d400-45ea-9c79-b386c123ed8c', 'workflow_id': '556db796-dd96-4ccc-a317-068b9d8d72ba', 'workflow_run_id': '56bc9036-0768-4a2d-a521-a72058b3b415', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.activity:_activity.py:463 Completing asynchronously ({'activity_id': '1', 'activity_type': 'run', 'attempt': 1, 'namespace': 'default', 'task_queue': '3a2d4a37-d400-45ea-9c79-b386c123ed8c', 'workflow_id': '556db796-dd96-4ccc-a317-068b9d8d72ba', 'workflow_run_id': '56bc9036-0768-4a2d-a521-a72058b3b415', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\n$e6d2a310-ce30-4dfe-87db-9ed829a8df47\022$556db796-dd96-4ccc-a317-068b9d8d72ba\032$56bc9036-0768-4a2d-a521-a72058b3b415 \005(\0012\0011B\003runJ\010\010\001\020\265\226@\030\001"
result {
  will_complete_async {
  }
}

DEBUG    temporalio.worker._activity:_activity.py:276 Running activity run (token b'\n$e6d2a310-ce30-4dfe-87db-9ed829a8df47\x12$556db796-dd96-4ccc-a317-068b9d8d72ba\x1a$56bc9036-0768-4a2d-a521-a72058b3b415 \x05(\x022\x011B\x03runJ\x08\x08\x01\x10\xb8\x96@\x18\x01')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'run', 'attempt': 2, 'namespace': 'default', 'task_queue': '3a2d4a37-d400-45ea-9c79-b386c123ed8c', 'workflow_id': '556db796-dd96-4ccc-a317-068b9d8d72ba', 'workflow_run_id': '56bc9036-0768-4a2d-a521-a72058b3b415', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.activity:_activity.py:463 Completing asynchronously ({'activity_id': '1', 'activity_type': 'run', 'attempt': 2, 'namespace': 'default', 'task_queue': '3a2d4a37-d400-45ea-9c79-b386c123ed8c', 'workflow_id': '556db796-dd96-4ccc-a317-068b9d8d72ba', 'workflow_run_id': '56bc9036-0768-4a2d-a521-a72058b3b415', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\n$e6d2a310-ce30-4dfe-87db-9ed829a8df47\022$556db796-dd96-4ccc-a317-068b9d8d72ba\032$56bc9036-0768-4a2d-a521-a72058b3b415 \005(\0022\0011B\003runJ\010\010\001\020\270\226@\030\001"
result {
  will_complete_async {
  }
}

DEBUG    temporalio.worker._workflow_instance:_workflow_instance.py:1788 Workflow raised failure with run ID 56bc9036-0768-4a2d-a521-a72058b3b415
temporalio.exceptions.ApplicationError: err message 2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 1767, in _run_top_level_workflow_function
    await coro
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 831, in run_workflow
    result = await self._inbound.execute_workflow(input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/temporalio/testing/_workflow.py", line 493, in execute_workflow
    return await super().execute_workflow(input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_interceptor.py", line 328, in execute_workflow
    return await self.next.execute_workflow(input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 2099, in execute_workflow
    return await input.run_fn(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/tests/helpers/worker.py", line 97, in run
    should_return, ret = await self.handle_action(params, action)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/tests/helpers/worker.py", line 204, in handle_action
    raise task.exception()  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/tests/helpers/worker.py", line 193, in run_activity
    last_result = await task
                  ^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 1423, in run_activity
    return await asyncio.shield(handle._result_fut)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
temporalio.exceptions.ActivityError: Activity task failed
INFO     temporalio.worker._worker:_worker.py:523 Beginning worker shutdown, will wait 0:00:00 before cancelling activities