DEBUG    temporalio.worker._workflow:_workflow.py:299 Evicting workflow with run ID 9a0040ff-5c42-488b-90ae-660e5cba3f14, message: Workflow activation completion failed: Failure { failure: Some(Failure { message: "[TMPRL1100] Nondeterminism error: Timer machine does not handle this event: HistoryEvent(id: 11, WorkflowExecutionCompleted)", source: "", stack_trace: "", encoded_attributes: None, cause: None, failure_info: Some(ApplicationFailureInfo(ApplicationFailureInfo { r#type: "", non_retryable: false, details: None, next_retry_delay: None })) }), force_cause: NonDeterministicError }
DEBUG    temporalio.worker._workflow:_workflow.py:299 Evicting workflow with run ID 577fbf9c-bed0-4fcb-b582-3e7447adeca6, message: Always evict workflows after replay
DEBUG    temporalio.worker._workflow:_workflow.py:299 Evicting workflow with run ID r3, message: Always evict workflows after replay