DEBUG    temporalio.worker._activity:_activity.py:276 Running activity wait_cancel (token b'\n$e6d2a310-ce30-4dfe-87db-9ed829a8df47\x12-workflow-349be76a-ed79-48dd-bde9-7902239b4da0\x1a$dbf43dbc-d570-4f78-a116-0516853ae4a3 \x06(\x012\x011B\x0bwait_cancelJ\x08\x08\x01\x10\xee\xbf@\x18\x01')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'wait_cancel', 'attempt': 1, 'namespace': 'default', 'task_queue': '49801f76-d0e5-4560-9976-f80ef92447b8', 'workflow_id': 'workflow-349be76a-ed79-48dd-bde9-7902239b4da0', 'workflow_run_id': 'dbf43dbc-d570-4f78-a116-0516853ae4a3', 'workflow_type': 'TimeoutSupportWorkflow'})
DEBUG    temporalio.activity:_activity.py:255 Recording heartbeat with details () ({'activity_id': '1', 'activity_type': 'wait_cancel', 'attempt': 1, 'namespace': 'default', 'task_queue': '49801f76-d0e5-4560-9976-f80ef92447b8', 'workflow_id': 'workflow-349be76a-ed79-48dd-bde9-7902239b4da0', 'workflow_run_id': 'dbf43dbc-d570-4f78-a116-0516853ae4a3', 'workflow_type': 'TimeoutSupportWorkflow'})
DEBUG    temporalio.activity:_activity.py:255 Recording heartbeat with details () ({'activity_id': '1', 'activity_type': 'wait_cancel', 'attempt': 1, 'namespace': 'default', 'task_queue': '49801f76-d0e5-4560-9976-f80ef92447b8', 'workflow_id': 'workflow-349be76a-ed79-48dd-bde9-7902239b4da0', 'workflow_run_id': 'dbf43dbc-d570-4f78-a116-0516853ae4a3', 'workflow_type': 'TimeoutSupportWorkflow'})
DEBUG    temporalio.worker._workflow_instance:_workflow_instance.py:1788 Workflow raised failure with run ID dbf43dbc-d570-4f78-a116-0516853ae4a3
temporalio.exceptions.CancelledError: Cancelled

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 1767, in _run_top_level_workflow_function
    await coro
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 831, in run_workflow
    result = await self._inbound.execute_workflow(input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/temporalio/testing/_workflow.py", line 493, in execute_workflow
    return await super().execute_workflow(input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_interceptor.py", line 328, in execute_workflow
    return await self.next.execute_workflow(input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 2099, in execute_workflow
    return await input.run_fn(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/tests/worker/test_workflow.py", line 4609, in run
    await workflow.execute_activity(
  File "/home/runner/work/sdk-python/sdk-python/temporalio/workflow.py", line 2011, in execute_activity
    return await _Runtime.current().workflow_start_activity(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 1423, in run_activity
    return await asyncio.shield(handle._result_fut)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
temporalio.exceptions.ActivityError: Activity cancelled
INFO     temporalio.worker._worker:_worker.py:523 Beginning worker shutdown, will wait 0:00:00 before cancelling activities
DEBUG    temporalio.worker._activity:_activity.py:216 Cancelling activity b'\n$e6d2a310-ce30-4dfe-87db-9ed829a8df47\x12-workflow-349be76a-ed79-48dd-bde9-7902239b4da0\x1a$dbf43dbc-d570-4f78-a116-0516853ae4a3 \x06(\x012\x011B\x0bwait_cancelJ\x08\x08\x01\x10\xee\xbf@\x18\x01', reason: 3
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\n$e6d2a310-ce30-4dfe-87db-9ed829a8df47\022-workflow-349be76a-ed79-48dd-bde9-7902239b4da0\032$dbf43dbc-d570-4f78-a116-0516853ae4a3 \006(\0012\0011B\013wait_cancelJ\010\010\001\020\356\277@\030\001"
result {
  completed {
    result {
      metadata {
        key: "encoding"
        value: "json/plain"
      }
      data: "\"Got cancelled error, cancelled? True\""
    }
  }
}