DEBUG    temporalio.worker._activity:_activity.py:276 Running activity run (token b'\x00\x07default\x00$fb50240a-7562-4c22-82ae-daba6693cb08\x00$31c22bc0-727d-4f2e-ab6f-1beea50fd4ec\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x01')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'run', 'attempt': 1, 'namespace': 'default', 'task_queue': '7b12b619-5bc4-4e2b-a261-78dfd1920c3b', 'workflow_id': 'fb50240a-7562-4c22-82ae-daba6693cb08', 'workflow_run_id': '31c22bc0-727d-4f2e-ab6f-1beea50fd4ec', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.activity:_activity.py:463 Completing asynchronously ({'activity_id': '1', 'activity_type': 'run', 'attempt': 1, 'namespace': 'default', 'task_queue': '7b12b619-5bc4-4e2b-a261-78dfd1920c3b', 'workflow_id': 'fb50240a-7562-4c22-82ae-daba6693cb08', 'workflow_run_id': '31c22bc0-727d-4f2e-ab6f-1beea50fd4ec', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\000\007default\000$fb50240a-7562-4c22-82ae-daba6693cb08\000$31c22bc0-727d-4f2e-ab6f-1beea50fd4ec\000\000\000\000\000\000\000\005\000\000\000\001"
result {
  will_complete_async {
  }
}

DEBUG    temporalio.worker._activity:_activity.py:276 Running activity run (token b'\x00\x07default\x00$fb50240a-7562-4c22-82ae-daba6693cb08\x00$31c22bc0-727d-4f2e-ab6f-1beea50fd4ec\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x02')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'run', 'attempt': 2, 'namespace': 'default', 'task_queue': '7b12b619-5bc4-4e2b-a261-78dfd1920c3b', 'workflow_id': 'fb50240a-7562-4c22-82ae-daba6693cb08', 'workflow_run_id': '31c22bc0-727d-4f2e-ab6f-1beea50fd4ec', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.activity:_activity.py:463 Completing asynchronously ({'activity_id': '1', 'activity_type': 'run', 'attempt': 2, 'namespace': 'default', 'task_queue': '7b12b619-5bc4-4e2b-a261-78dfd1920c3b', 'workflow_id': 'fb50240a-7562-4c22-82ae-daba6693cb08', 'workflow_run_id': '31c22bc0-727d-4f2e-ab6f-1beea50fd4ec', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\000\007default\000$fb50240a-7562-4c22-82ae-daba6693cb08\000$31c22bc0-727d-4f2e-ab6f-1beea50fd4ec\000\000\000\000\000\000\000\005\000\000\000\002"
result {
  will_complete_async {
  }
}

DEBUG    temporalio.worker._workflow_instance:_workflow_instance.py:1788 Workflow raised failure with run ID 31c22bc0-727d-4f2e-ab6f-1beea50fd4ec
temporalio.exceptions.ApplicationError: err message 2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 1767, in _run_top_level_workflow_function
    await coro
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 831, in run_workflow
    result = await self._inbound.execute_workflow(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/testing/_workflow.py", line 493, in execute_workflow
    return await super().execute_workflow(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_interceptor.py", line 328, in execute_workflow
    return await self.next.execute_workflow(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 2099, in execute_workflow
    return await input.run_fn(*args)
  File "/home/runner/work/sdk-python/sdk-python/tests/helpers/worker.py", line 97, in run
    should_return, ret = await self.handle_action(params, action)
  File "/home/runner/work/sdk-python/sdk-python/tests/helpers/worker.py", line 204, in handle_action
    raise task.exception()  # type: ignore
  File "/home/runner/work/sdk-python/sdk-python/tests/helpers/worker.py", line 193, in run_activity
    last_result = await task
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 1423, in run_activity
    return await asyncio.shield(handle._result_fut)
temporalio.exceptions.ActivityError: Activity task failed
INFO     temporalio.worker._worker:_worker.py:523 Beginning worker shutdown, will wait 0:00:00 before cancelling activities