DEBUG    temporalio.worker._activity:_activity.py:276 Running activity picklable_activity_raise_cancel (token b'\n$f032a326-ed6d-485e-81c8-68533bd3a6fc\x12$0948a59f-c881-4774-9e71-5922cbbba254\x1a$c964055b-8e5f-4f76-874e-c14d036b98ee \x05(\x012\x011B\x1fpicklable_activity_raise_cancelJ\x08\x08\x01\x10\xb6\x8f@\x18\x01')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'picklable_activity_raise_cancel', 'attempt': 1, 'namespace': 'default', 'task_queue': 'fba72f85-fc35-4fca-8d07-62e5bb0fe949', 'workflow_id': '0948a59f-c881-4774-9e71-5922cbbba254', 'workflow_run_id': 'c964055b-8e5f-4f76-874e-c14d036b98ee', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.activity:_activity.py:255 Recording heartbeat with details () ({'activity_id': '1', 'activity_type': 'picklable_activity_raise_cancel', 'attempt': 1, 'namespace': 'default', 'task_queue': 'fba72f85-fc35-4fca-8d07-62e5bb0fe949', 'workflow_id': '0948a59f-c881-4774-9e71-5922cbbba254', 'workflow_run_id': 'c964055b-8e5f-4f76-874e-c14d036b98ee', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.worker._activity:_activity.py:216 Cancelling activity b'\n$f032a326-ed6d-485e-81c8-68533bd3a6fc\x12$0948a59f-c881-4774-9e71-5922cbbba254\x1a$c964055b-8e5f-4f76-874e-c14d036b98ee \x05(\x012\x011B\x1fpicklable_activity_raise_cancelJ\x08\x08\x01\x10\xb6\x8f@\x18\x01', reason: 1
DEBUG    temporalio.activity:_activity.py:255 Recording heartbeat with details () ({'activity_id': '1', 'activity_type': 'picklable_activity_raise_cancel', 'attempt': 1, 'namespace': 'default', 'task_queue': 'fba72f85-fc35-4fca-8d07-62e5bb0fe949', 'workflow_id': '0948a59f-c881-4774-9e71-5922cbbba254', 'workflow_run_id': 'c964055b-8e5f-4f76-874e-c14d036b98ee', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.activity:_activity.py:486 Completing as cancelled ({'activity_id': '1', 'activity_type': 'picklable_activity_raise_cancel', 'attempt': 1, 'namespace': 'default', 'task_queue': 'fba72f85-fc35-4fca-8d07-62e5bb0fe949', 'workflow_id': '0948a59f-c881-4774-9e71-5922cbbba254', 'workflow_run_id': 'c964055b-8e5f-4f76-874e-c14d036b98ee', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\n$f032a326-ed6d-485e-81c8-68533bd3a6fc\022$0948a59f-c881-4774-9e71-5922cbbba254\032$c964055b-8e5f-4f76-874e-c14d036b98ee \005(\0012\0011B\037picklable_activity_raise_cancelJ\010\010\001\020\266\217@\030\001"
result {
  cancelled {
    failure {
      message: "Cancelled"
      canceled_failure_info {
      }
    }
  }
}

DEBUG    temporalio.worker._workflow_instance:_workflow_instance.py:1788 Workflow raised failure with run ID c964055b-8e5f-4f76-874e-c14d036b98ee
temporalio.exceptions.CancelledError: Cancelled

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 1767, in _run_top_level_workflow_function
    await coro
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 831, in run_workflow
    result = await self._inbound.execute_workflow(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/testing/_workflow.py", line 493, in execute_workflow
    return await super().execute_workflow(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_interceptor.py", line 328, in execute_workflow
    return await self.next.execute_workflow(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 2099, in execute_workflow
    return await input.run_fn(*args)
  File "/home/runner/work/sdk-python/sdk-python/tests/helpers/worker.py", line 97, in run
    should_return, ret = await self.handle_action(params, action)
  File "/home/runner/work/sdk-python/sdk-python/tests/helpers/worker.py", line 204, in handle_action
    raise task.exception()  # type: ignore
  File "/home/runner/work/sdk-python/sdk-python/tests/helpers/worker.py", line 193, in run_activity
    last_result = await task
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 1423, in run_activity
    return await asyncio.shield(handle._result_fut)
temporalio.exceptions.ActivityError: Activity cancelled
INFO     temporalio.worker._worker:_worker.py:523 Beginning worker shutdown, will wait 0:00:00 before cancelling activities