DEBUG    temporalio.worker._activity:_activity.py:276 Running activity picklable_heartbeat_details_activity (token b'\n$e6d2a310-ce30-4dfe-87db-9ed829a8df47\x12$2b930857-39dd-47e5-a932-70dc6f67129d\x1a$4ab78a33-8cd7-474b-b9b6-ab263555b3b8 \x05(\x012\x011B$picklable_heartbeat_details_activityJ\x08\x08\x01\x10\xdb\x92@\x18\x01')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'picklable_heartbeat_details_activity', 'attempt': 1, 'namespace': 'default', 'task_queue': '2abd64c4-c4dc-42d2-baf2-273ef4e2a6dc', 'workflow_id': '2b930857-39dd-47e5-a932-70dc6f67129d', 'workflow_run_id': '4ab78a33-8cd7-474b-b9b6-ab263555b3b8', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.activity:_activity.py:255 Recording heartbeat with details (['attempt: 1'],) ({'activity_id': '1', 'activity_type': 'picklable_heartbeat_details_activity', 'attempt': 1, 'namespace': 'default', 'task_queue': '2abd64c4-c4dc-42d2-baf2-273ef4e2a6dc', 'workflow_id': '2b930857-39dd-47e5-a932-70dc6f67129d', 'workflow_run_id': '4ab78a33-8cd7-474b-b9b6-ab263555b3b8', 'workflow_type': 'kitchen_sink'})
WARNING  temporalio.activity:_activity.py:493 Completing activity as failed ({'activity_id': '1', 'activity_type': 'picklable_heartbeat_details_activity', 'attempt': 1, 'namespace': 'default', 'task_queue': '2abd64c4-c4dc-42d2-baf2-273ef4e2a6dc', 'workflow_id': '2b930857-39dd-47e5-a932-70dc6f67129d', 'workflow_run_id': '4ab78a33-8cd7-474b-b9b6-ab263555b3b8', 'workflow_type': 'kitchen_sink'})
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.5/arm64/lib/python3.12/concurrent/futures/process.py", line 263, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py", line 774, in _execute_sync_activity
    return fn(*args)
           ^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/tests/worker/test_activity.py", line 696, in picklable_heartbeat_details_activity
    raise RuntimeError(f"Try again, list contains: {some_list}")
RuntimeError: Try again, list contains: ['attempt: 1']
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py", line 453, in _run_activity
    result = await impl.execute_activity(input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py", line 705, in execute_activity
    return await loop.run_in_executor(input.executor, func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Try again, list contains: ['attempt: 1']
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\n$e6d2a310-ce30-4dfe-87db-9ed829a8df47\022$2b930857-39dd-47e5-a932-70dc6f67129d\032$4ab78a33-8cd7-474b-b9b6-ab263555b3b8 \005(\0012\0011B$picklable_heartbeat_details_activityJ\010\010\001\020\333\222@\030\001"
result {
  failed {
    failure {
      message: "Try again, list contains: [\'attempt: 1\']"
      stack_trace: "  File \"/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py\", line 453, in _run_activity\n    result = await impl.execute_activity(input)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py\", line 705, in execute_activity\n    return await loop.run_in_executor(input.executor, func, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"
      cause {
        message: "\n\"\"\"\nTraceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.5/arm64/lib/python3.12/concurrent/futures/process.py\", line 263, in _process_worker\n    r = call_item.fn(*call_item.args, **call_item.kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py\", line 774, in _execute_sync_activity\n    return fn(*args)\n           ^^^^^^^^^\n  File \"/home/runner/work/sdk-python/sdk-python/tests/worker/test_activity.py\", line 696, in picklable_heartbeat_details_activity\n    raise RuntimeError(f\"Try again, list contains: {some_list}\")\nRuntimeError: Try again, list contains: [\'attempt: 1\']\n\"\"\""
        application_failure_info {
          type: "_RemoteTraceback"
        }
      }
      application_failure_info {
        type: "RuntimeError"
      }
    }
  }
}

DEBUG    temporalio.worker._activity:_activity.py:276 Running activity picklable_heartbeat_details_activity (token b'\n$e6d2a310-ce30-4dfe-87db-9ed829a8df47\x12$2b930857-39dd-47e5-a932-70dc6f67129d\x1a$4ab78a33-8cd7-474b-b9b6-ab263555b3b8 \x05(\x022\x011B$picklable_heartbeat_details_activityJ\x08\x08\x01\x10\xde\x92@\x18\x01')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'picklable_heartbeat_details_activity', 'attempt': 2, 'namespace': 'default', 'task_queue': '2abd64c4-c4dc-42d2-baf2-273ef4e2a6dc', 'workflow_id': '2b930857-39dd-47e5-a932-70dc6f67129d', 'workflow_run_id': '4ab78a33-8cd7-474b-b9b6-ab263555b3b8', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.activity:_activity.py:255 Recording heartbeat with details (['attempt: 1', 'attempt: 2'],) ({'activity_id': '1', 'activity_type': 'picklable_heartbeat_details_activity', 'attempt': 2, 'namespace': 'default', 'task_queue': '2abd64c4-c4dc-42d2-baf2-273ef4e2a6dc', 'workflow_id': '2b930857-39dd-47e5-a932-70dc6f67129d', 'workflow_run_id': '4ab78a33-8cd7-474b-b9b6-ab263555b3b8', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\n$e6d2a310-ce30-4dfe-87db-9ed829a8df47\022$2b930857-39dd-47e5-a932-70dc6f67129d\032$4ab78a33-8cd7-474b-b9b6-ab263555b3b8 \005(\0022\0011B$picklable_heartbeat_details_activityJ\010\010\001\020\336\222@\030\001"
result {
  completed {
    result {
      metadata {
        key: "encoding"
        value: "json/plain"
      }
      data: "\"attempt: 1, attempt: 2\""
    }
  }
}

INFO     temporalio.worker._worker:_worker.py:523 Beginning worker shutdown, will wait 0:00:00 before cancelling activities