DEBUG    temporalio.worker._activity:_activity.py:276 Running activity say_hello (token b'\n$8aa290fa-b00f-4fa1-a139-85696fcc157a\x12$ef521415-6064-4cd0-9574-176f895b285c\x1a$d19dcddc-7809-4acc-9de3-15732ef14d92 \x05(\x012\x011B\tsay_helloJ\x08\x08\x01\x10\xb2\x8c@\x18\x01')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'say_hello', 'attempt': 1, 'namespace': 'default', 'task_queue': '634694d8-38a6-4eac-b697-3e82a61d7a7b', 'workflow_id': 'ef521415-6064-4cd0-9574-176f895b285c', 'workflow_run_id': 'd19dcddc-7809-4acc-9de3-15732ef14d92', 'workflow_type': 'kitchen_sink'})
WARNING  temporalio.activity:_activity.py:493 Completing activity as failed ({'activity_id': '1', 'activity_type': 'say_hello', 'attempt': 1, 'namespace': 'default', 'task_queue': '634694d8-38a6-4eac-b697-3e82a61d7a7b', 'workflow_id': 'ef521415-6064-4cd0-9574-176f895b285c', 'workflow_run_id': 'd19dcddc-7809-4acc-9de3-15732ef14d92', 'workflow_type': 'kitchen_sink'})
Traceback (most recent call last):
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py", line 453, in _run_activity
    result = await impl.execute_activity(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py", line 711, in execute_activity
    return await input.fn(*input.args)
TypeError: say_hello() missing 1 required positional argument: 'name'
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\n$8aa290fa-b00f-4fa1-a139-85696fcc157a\022$ef521415-6064-4cd0-9574-176f895b285c\032$d19dcddc-7809-4acc-9de3-15732ef14d92 \005(\0012\0011B\tsay_helloJ\010\010\001\020\262\214@\030\001"
result {
  failed {
    failure {
      message: "say_hello() missing 1 required positional argument: \'name\'"
      stack_trace: "  File \"/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py\", line 453, in _run_activity\n    result = await impl.execute_activity(input)\n\n  File \"/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py\", line 711, in execute_activity\n    return await input.fn(*input.args)\n"
      application_failure_info {
        type: "TypeError"
      }
    }
  }
}

DEBUG    temporalio.worker._workflow_instance:_workflow_instance.py:1788 Workflow raised failure with run ID d19dcddc-7809-4acc-9de3-15732ef14d92
temporalio.exceptions.ApplicationError: TypeError: say_hello() missing 1 required positional argument: 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 1767, in _run_top_level_workflow_function
    await coro
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 831, in run_workflow
    result = await self._inbound.execute_workflow(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/testing/_workflow.py", line 493, in execute_workflow
    return await super().execute_workflow(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_interceptor.py", line 328, in execute_workflow
    return await self.next.execute_workflow(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 2099, in execute_workflow
    return await input.run_fn(*args)
  File "/home/runner/work/sdk-python/sdk-python/tests/helpers/worker.py", line 97, in run
    should_return, ret = await self.handle_action(params, action)
  File "/home/runner/work/sdk-python/sdk-python/tests/helpers/worker.py", line 204, in handle_action
    raise task.exception()  # type: ignore
  File "/home/runner/work/sdk-python/sdk-python/tests/helpers/worker.py", line 193, in run_activity
    last_result = await task
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 1423, in run_activity
    return await asyncio.shield(handle._result_fut)
temporalio.exceptions.ActivityError: Activity task failed
INFO     temporalio.worker._worker:_worker.py:523 Beginning worker shutdown, will wait 0:00:00 before cancelling activities